urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'furugi'
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('user-profile', views.user_profile, name="user-profile"),
    path('view-profile', views.view_profile, name="view-profile"),
    path('user-ads', views.user_ads, name="user-ads"),
    path('user-favorites', views.user_favorites, name="user-favorites"),
    path('add-favorites/<int:id>', views.add_user_favorites, name="add-favorites"),
    path('remove-favorites/<int:id>', views.remove_user_favorites, name="remove-favorites"),
    path('ad-create', views.add_advertisment, name="create"),
    path('ad-view/<int:id>/<slug>', views.view_advertisment, name="view"),
    path('ad-edit/<int:id>', views.edit_advertisment, name="edit"),
    path('ad-delete/<int:id>', views.delete_advertisment, name="delete"),   
    path('ad-review', views.add_review, name="ad-review"),   
    path('ads', views.ads, name="ads"),
    path('thread/<int:u_id>/<int:d_id>', views.create_thread, name="thread"),
    path('chatbox', views.chatbox, name="chatbox"),
    path('get-messages', views.get_messages, name="get-messages"),
    path('post-message', views.post_message, name="post-message"),
    path('ads/tag/<slug>', views.filtered_ads, name="tagged"),
    path('report/<int:u_id>/<int:d_id>', views.report_user, name="report"),
    path('block/<id>/', views.block_user, name="block"),
    path('thread/ad-view/<int:id>', views.thread_advertisment),
    path('get-notifications', views.get_notifications, name="get-notifications"),
    path('search-results', views.search_results, name="searching"),
    path('contact', views.contact, name="contact"),
    path('terms-and-conditions', views.terms_and_conditions, name="terms-and-conditions"),
    path('privacy-policy', views.privacy_policy, name="privacy-policy"),
    path('about', views.about, name="about"),
    path('404', views.error_404, name="404"),
    path('admin/user-management', views.user_management , name = 'user-management'),
    path('deactivate-user/<int:id>', views.deactivate_user, name = 'deactivate-user'),
    path('activate-user/<int:id>', views.activate_user, name = 'activate-user'),
    path('admin/user-reporting', views.user_reporting , name = 'user-reporting'),
    path('blog/<slug>', views.blog_view , name = 'blog'),
    path('blogs', views.blogs , name = 'blogs'),
    path('pics/<pic>', views.add_advertisment_pictures , name = 'pics'),
    path('custom/admin', views.admin_dashboard , name = 'custom-admin'),
    path('add-to-cart', views.add_to_cart , name = 'add-to-cart'),
    path('user-cart', views.user_cart , name = 'cart'),
    path('user-orders', views.user_orders , name = 'orders'),
    path('delete-item/<id>', views.delete_item , name = 'delete-item'),
    path('create-order', views.create_order , name = 'order'),
    path('deliver-order/<id>', views.deliver_order , name = 'deliver'),
    path('cancel-order/<id>', views.cancel_order , name = 'cancel'),
    path('delete-order/<id>', views.delete_order , name = 'delete'),
    path('dispatch-order/<id>', views.dispatch_order , name = 'dispatch'),
    path('get-items', views.get_items, name='get-items'),
    path('past-orders', views.past_orders , name = 'past-orders'),
    path('orders-history', views.orders_history , name = 'orders-history'),
    path('get-orders', views.get_orders , name = 'get-orders'),
    path('category/<category>', views.category_results, name="category"),
    path('delete/thread/<id>', views.delete_thread, name="delete-thread"),
    path('sort', views.sort_ads , name = 'sort'),
]

views/base.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from ..models import Dress, Dress_Pictures, Trending, Personal_Details, Favorites, Dress_Rating, Thread, Chat, User_Thread, Ad_Thread, Blog
from datetime import datetime, date
from django.templatetags.static import static
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from taggit.models import Tag
from django.core.mail import send_mail
from django.db.models import Avg
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from random import randrange

def index(request):
    try:
        latest = Dress.objects.all().order_by('-posted_date')[:40]
    except Dress.DoesNotExist:
        raise Http404()
    try:
        trending = Trending.objects.all()
        start = randrange(15,25)        
        rated = Dress.objects.annotate(stars = Avg('dress_rating__stars')).order_by('-posted_date')[start:][:11]
        #rated = Dress.objects.annotate(stars = Avg('dress_rating__stars')).order_by('-views')[:11]
    except Dress.DoesNotExist:
        raise Http404()
    try:
        start = randrange(5,45)        
        popular = Dress.objects.annotate(stars = Avg('dress_rating__stars')).order_by('-views')[start:][:9]
    except Dress.DoesNotExist:
        raise Http404()
    try:
        blog = Blog.objects.all().order_by('-date')[:3]
    except Blog.DoesNotExist:
        raise Http404()
    
    data = {'trending': trending, 'rated': rated , "popular": popular , "latest": latest, "blogs": blog }
    return render(request, 'furugi/index.html', data) 

@login_required
def get_notifications(request):
    user_thread = User_Thread.objects.filter(sender = request.user) 
    chat = 0   
    for user in user_thread:
        data = Chat.objects.filter(thread = user.thread, user= user.reciever, read = 0).count()
        chat += data    
    return JsonResponse({ 'data' :chat})

def blog_view(request, slug):
    blogs = Blog.objects.filter(slug = slug)
    data = {"blog": blogs[0]}
    return render(request, 'furugi/blogs/view.html', data)

def blogs(request):
    blogs = Blog.objects.all().order_by('-date')
    page = request.GET.get('page', 1)
    paginator = Paginator(blogs, 16)
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        bolgs = paginator.page(paginator.num_pages)
    data = {"blogs": blogs}
    return render(request, 'furugi/blogs/listing.html', data)

def contact(request):
    if request.POST:
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
  
        subject = request.POST.get('subject')
        msg = request.POST.get('message')
        html = 'Name = '+fname+' '+lname +' Message = '+msg+'';
        html_message = render_to_string('furugi/emails/contact.html', {'fname': fname, 'lname' : lname, 'msg' : msg, 'email' : email}
        plain_message = strip_tags(html_message)
        send_mail(subject, plain_message, email, ['contact@furugi.com.pk'], html_message = html_message)
        messages.add_message(request, messages.SUCCESS, 'Email has been sent.')  
        return render(request, 'furugi/contact.html')      
    else:
        return render(request, 'furugi/contact.html')

def terms_and_conditions(request):
    return render(request, 'furugi/terms&conditions.html')

def privacy_policy(request):
    return render(request, 'furugi/privacy_policy.html')

def about(request):
    return render(request, 'furugi/about.html')

def error_404(request, exception):
    return render(request, 'furugi/404.html')

def error_500(request):
    return render(request, 'furugi/500.html')

templates/furugi/partials/footer.html
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-5">
                <h2 class="footer-heading mb-4">About</h2>
                <p>Furugi - A platform that aims helping people with local businesses and gives opportunity to anyone to advertise their clothes online in Pakistan.
                  <a href="{% url 'furugi:about' %}">Learn more..</a> </p>
              </div>
              <div class="col-md-3">
                <h2 class="footer-heading mb-4">Navigations</h2>
                <ul class="list-unstyled">
                  <li><a href="{% url 'furugi:ads' %}">Ads</a></li>
                  <li><a href="{% url 'furugi:blogs' %}">Blogs</a></li>
                  <li><a href="{% url 'furugi:terms-and-conditions' %}">Terms and Conditions</a></li>
                  <li><a href="{% url 'furugi:privacy-policy' %}">Privacy policy</a></li>
                  <li><a href="{% url 'furugi:contact' %}">Contact Us</a></li>
                </ul>
              </div>
              <div class="col-md-4">
                <h2 class="footer-heading mb-4">Follow Us</h2>
                <a href="https://www.facebook.com/Furugi.pk/" class="pl-0 pr-3"><span class="icon-facebook"></span></a>
                <a href="https://twitter.com/furugi_pk" class="pl-3 pr-3"><span class="icon-twitter"></span></a>
                <a href="https://instagram.com/furugi_pk" class="pl-3 pr-3"><span class="icon-instagram"></span></a>
                <a href="https://www.linkedin.com/company/65822759" class="pl-3 pr-3"><span class="icon-linkedin"></span></a>
              </div>
            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
            <p>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> Furugi. All rights reserved 
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

templates/furugi/partials/header.html
<link rel="stylesheet" href=https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css>
<style>
  /* The sticky class is added to the navbar with JS when it reaches its scroll position */
  .sticky {
    position: fixed !important;
    top: 0;
    width: 100%;
    padding-top: 200px;
  }
  #categories {

    overflow-y: scroll;
    
    height: 400px;
    
    }
</style>
<header class="site-navbar container py-0 bg-white" role="banner" id="navbar">
        <div class="row align-items-center">

          <div class="col-6 col-xl-2">
            <h1 class="mb-0 site-logo"><a href="{% url 'furugi:index' %}" class="text-black mb-0">Furu<span class="text-primary">gi</span>  </a></h1>
          </div>
          <div class="col-12 col-md-10 d-none d-xl-block">
            <nav class="site-navigation position-relative text-right" role="navigation">
            
              <ul class="site-menu js-clone-nav mr-auto d-none d-lg-block" id="header-ul">
                <li ><a href="{% url 'furugi:index' %}">Home</a></li>
                
                <li class="has-children" > <a href="{% url 'furugi:ads' %}">Categories</a>             
                  <ul class="dropdown" id="categories">
                    <li><a href="{% url 'furugi:ads' %}">---All---</a></li>
                    <li><a href="{% url 'furugi:category' 'Summer Wear' %}">Summer Wear</a></li>
                    <li><a href="{% url 'furugi:category' 'Bridal Wear' %}">Bridal Wear</a></li>
                    <li><a href="{% url 'furugi:category' 'Party Wear' %}">Party Wear</a></li>
                    <li><a href="{% url 'furugi:category' 'Couture' %}">Couture</a></li>
                    <li><a href="{% url 'furugi:category' 'Traditional' %}">Traditional</a></li>
                    <li><a href="{% url 'furugi:category' 'Western Wear' %}">Western Wear</a></li>
                    <li><a href="{% url 'furugi:category' 'Sweaters & Jackets' %}">Sweaters & Jackets</a></li>
                    <li><a href="{% url 'furugi:category' 'Pent & Shirts' %}">Pent & Shirts</a></li>
                    <li><a href="{% url 'furugi:category' 'Winter Wear' %}">Winter Wear</a></li>
                    <li><a href="{% url 'furugi:category' 'Night Suits' %}">Night Suits</a></li>
                    <li><a href="{% url 'furugi:category' 'Footwear' %}">Footwear</a></li>
                    <li><a href="{% url 'furugi:category' 'Accessories' %}">Accessories</a></li>
                    <li><a href="{% url 'furugi:category' 'Jewellery' %}">Jewellery</a></li>
                    <li><a href="{% url 'furugi:category' 'Make-up' %}">Make-up</a></li>
                    <li><a href="{% url 'furugi:category' 'Skin & Hair' %}">Skin & Hair</a></li>
                    <li><a href="{% url 'furugi:category' 'Watches' %}">Watches</a></li>
                    <li><a href="{% url 'furugi:category' 'Other' %}">Other</a></li>
                  </ul>
                </li>
                <li ><a href="{% url 'furugi:chatbox' %}"  class="notifications">Chatbox</a></li> 
                <li><a href="{% url 'furugi:orders' %}" style="color:red" class="orders">Orders</a></li>           
                <li><a href="{% url 'furugi:cart' %}" class="cart" title="cart"><i class="fa fa-shopping-bag" style="color:black"></i></a></li>   
                <li><a href="{% url 'furugi:create' %}" class="cta"><span class="bg-primary text-white rounded">+ Post an Ad</span></a></li>
               
               
                {% if user.is_authenticated %}
              
                 <li class="has-children" > <a >{{ user.username }}</a>                
                 
                  <ul class="dropdown">
                   <li><a href="{% url 'furugi:user-profile' %}">My Profile</a></li>
                   <li><a href="{% url 'furugi:user-ads' %}">My Ads</a></li>               
                   <li><a href="{% url 'furugi:user-favorites' %}">Favourites</a></li>                    
                   <li><a href="{% url 'furugi:logout' %}">Logout</a></li>
                  </ul>
                </li>
                   
               {% else %}
               <li class="ml-xl-3 register"><a href="{% url 'furugi:register' %}">Register</a></li>
              
                  <li class="ml-xl-3 login"><a href="{% url 'furugi:login' %}"><span class="border-left pl-xl-4"></span>Log In</a></li>
              
               {% endif %}
          
              </ul>
            </nav>
          </div>
          <div class="d-inline-block d-xl-none ml-auto py-3 col-6 text-right" style="position: relative; top: 3px;">
            <a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a>
          </div>

        </div>
   
    </header>
<script>
  // When the user scrolls the page, execute myFunction
window.onscroll = function() {myFunction()};

// Get the navbar
var navbar = document.getElementById("navbar");

// Get the offset position of the navbar
var sticky = navbar.offsetTop;

// Add the sticky class to the navbar when you reach its scroll position. Remove "sticky" when you leave the scroll position
function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}

</script>

templates/furugi/partials/index_ad.html
    
        <div class="overlap-category mb-5">
          <div class="row align-items-stretch no-gutters">
            <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
              <a href="#" class="popular-category h-100">
                <span class="icon"><span class="flaticon-house"></span></span>
                <span class="caption mb-2 d-block">Real Estate</span>
                <span class="number">3,921</span>
              </a>
            </div>
            <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
              <a href="#" class="popular-category h-100">
                <span class="icon"><span class="flaticon-books"></span></span>
                <span class="caption mb-2 d-block">Books &amp; Magazines</span>
                <span class="number">398</span>
              </a>
            </div>
            <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
              <a href="#" class="popular-category h-100">
                <span class="icon"><span class="flaticon-bunk-bed"></span></span>
                <span class="caption mb-2 d-block">Furniture</span>
                <span class="number">1,229</span>
              </a>
            </div>
            <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
              <a href="#" class="popular-category h-100">
                <span class="icon"><span class="flaticon-innovation"></span></span>
                <span class="caption mb-2 d-block">Electronics</span>
                <span class="number">32,891</span>
              </a>
            </div>
            <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
              <a href="#" class="popular-category h-100">
                <span class="icon"><span class="flaticon-car"></span></span>
                <span class="caption mb-2 d-block">Cars &amp; Vehicles</span>
                <span class="number">29,221</span>
              </a>
            </div>
            <div class="col-sm-6 col-md-4 mb-4 mb-lg-0 col-lg-2">
              <a href="#" class="popular-category h-100">
                <span class="icon"><span class="flaticon-pizza"></span></span>
                <span class="caption mb-2 d-block">Other</span>
                <span class="number">219</span>
              </a>
            </div>
          </div>
        </div>

templates/furugi/partials/latest.html
<div class="row mb-5">
    <div class="col-md-7 text-left border-primary">
      <h2 class="font-weight-light text-primary">Latest Ads</h2>
    </div>
</div>
{% if latest.count > 4%}
<div class="row mt-5">
    <div class="col-12  block-13">
        <div class="owl-carousel nonloop-block-13">
         
    {% for data in latest %}   
    
    <div class="d-block d-md-flex listing vertical">
      <a href="{% url 'furugi:view' data.id data.slug %}" class="img d-block" style="background-image: url( '{{ data.profile.url}}')"></a>
      <div class="lh-content">
            <span class="category">{{data.category}}</span>
            <a href="{% url 'furugi:add-favorites' data.id %}" class="bookmark" data-toggle="tooltip" title="Add to favorites"><span class="icon-heart" ></span></a>
            <h3><a href="{% url 'furugi:view' data.id data.slug %}">{{ data.title}}</a></h3>
            {% if data.description == '' %}
            <address > (no description)</address>
            {% else %}
            <address >  {{ data.description}}</address>        
            {% endif %}   
            {% include 'furugi/advertisment/rating.html' %}    
            <strong>Price: {{ data.price}}</strong>
            <span class="review" style="float:right"><em><small> ({{ data.views}} Views)</small></em></span> 
           <div>                           
              {% for tag in data.tags.all|slice:':2' %}
                 <a href="{% url 'furugi:tagged' tag.slug %}" class="mr-1 badge badge-info">{{ tag.name }}</a>
              {% endfor %}
            </div>
          </div>     
        </div>
        {% if forloop.counter == 3 %}
        <div class="d-block d-md-flex listing vertical" style="background-color:#F1F6FB;border:#D6DFD8; height:410px">
            <div class="lh-content">
              <div class="lh-content" style="text-align:center; color:#879F9F; padding-top:55%">          
                <h4><b>Advertise Here</b></h4>                    
                <a href="{% url 'furugi:contact' %}" class="btn btn-info" style="color:white; border-color:grey; ">Contact Us</a>
         </div>    
            </div>     
        </div>
        {% endif %}
        <!-- {% if forloop.counter == 3 %}
        <div class="d-block d-md-flex listing vertical" style="background-color:#1cd1b7; height:430px">
            <div class="lh-content">
              <div class="lh-content" style="text-align:center; color:white; padding:10%">          
                <h4><b>Post Your Ad Here For Free</b></h4>
                <p> Spread your business online, and reach to costumers at large</p>
                <a href="{% url 'furugi:create' %}" class="btn btn-outline-info" style="color:white; border-color:white; ">Post Ad+</a>
            </div>    
            </div>     
        </div>
        {% endif %} -->
    {% endfor %}
</div>
</div>
</div>
{% else %}
<div style="text-align:center" ><h1> All latest ads would be displayed here</h1></div>
{% endif %}

templates/furugi/partials/mobile_menu.html
<div class="site-mobile-menu">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close mt-3">
        <span class="icon-close2 js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div>

templates/furugi/partials/newsletter.html
<div class="newsletter bg-primary py-5">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-1">
        </div>
        <div class="col-md-10" style="text-align:center">
          <h2 style="font-size:30px; font-weight:bold">How to get started with FURUGI?</h2>
      
           <p> Furugi is very simple and easy to use. The whole process takes around 2 minutes:  </p> 
          <div style="text-align:left; padding:0% 15%; color:white" >
           <ul >
            <li>Register your account at Furugi. It takes around half minute to register yourself at Furugi.</li>
            <li>Click on "+Post Ad".</li>
            <li>Write down the title of your Ad, description, add photos and select relevant options.</li>
            <li>Once you are done, click "Publish" and your Ad is live.</li>
          </ul>
        </div>
          <p>As soon as your Ad goes live, you will start to receive queries about your Ad and hopefully a good sale. Monitor your stats and orders from your very own personal dashboard</p>

           
        </div>
        <div class="col-md-1">
        </div>
      </div>
    </div>
  </div>

templates/furugi/partials/notification.html
{% if messages %}       
    {% for message in messages %}   
        {% if message.tags == 'success' %}             
            <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Success!</strong> {{ message }}
            </div>
        {% elif  message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Warning!</strong> {{ message }}
            </div>
        {% elif  message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Info!</strong> {{ message }}
            </div>
        {% endif %}
    {% endfor %}         
{% endif %}    

templates/furugi/partials/pagination.html
{% load static %}
<link rel="stylesheet" href="{% static 'furugi/css/pagination.css' %}">

<div class="center">    
    <div class="pagination">                
            {% if dresses.has_other_pages %}        
            {% if dresses.has_previous %}
                <a href="?page={{ dresses.previous_page_number }}">&laquo;</a>
            {% else %}
                <a  class="disabled"><span>&laquo;</span></a>
            {% endif %}
            {% for i in dresses.paginator.page_range %}
                {% if dresses.number == i %}
                <a class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                {% else %}
                <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
            {% if dresses.has_next %}
                <a href="?page={{ dresses.next_page_number }}">&raquo;</a>
            {% else %}
            <a class="disabled"><span>&laquo;</span></a>
            {% endif %}
            
        {% endif %}      
    </div>
</div>

templates/furugi/partials/popular.html
<div class="site-section" data-aos="fade">
  <div class="container">
    <div class="row justify-content-center mb-5">
      <div class="col-md-7 text-center border-primary">
        <h2 class="font-weight-light text-primary">Popular Products</h2>
        <p class="color-black-opacity-5">Ads with highest ratings</p>
      </div>
    </div>
    <div class="row">
      {% for data in popular %}
      <div class="col-md-6 mb-4 mb-lg-4 col-lg-4">
        <div class="listing-item">
          <div class="listing-image">
            <img src="{{ data.profile.url}}" alt="Image" style="height: 400px; width:300px ">
          </div>
          <div class="listing-item-content">
            <a href="{% url 'furugi:add-favorites' data.id %}" class="bookmark" data-toggle="tooltip" data-placement="left"
              title="Bookmark"><span class="icon-heart"></span></a>
            <a class="px-3 mb-3 category">{{data.category}}</a>
            <h2 class="mb-1"><a href="{% url 'furugi:view' data.id data.slug %}">{{ data.title}}</a></h2>
            <span class="address">Price : {{data.price}} </span>
            <div>
              {% for tag in data.tags.all|slice:':3' %}
              <a href="{% url 'furugi:tagged' tag.slug %}" class="mr-1 badge badge-info">{{ tag.name }}</a>
              {% endfor %}
            </div>
               <div class="fb-share-button" data-href="https://www.furugi.com.pk/ad-view/{{data.id}}/{{data.slug}}" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.furugi.com.pk%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
               
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

templates/furugi/partials/search.html
<div class="form-search-wrap" data-aos="fade-up" data-aos-delay="200">
    <form action="{% url 'furugi:searching' %}" method="post">
      {% csrf_token %}
      <div class="row align-items-center" style="text-align:center">
        <div class="col-lg-12 mb-4 mb-xl-0 col-xl-2"></div>
        <div class="col-lg-12 mb-4 mb-xl-0 col-xl-6 text-center" >
          <input type="text" class="form-control rounded" name="title" placeholder="What are you looking for?">
        </div>             
        <div class="col-lg-12 mb-4 mb-xl-0 col-xl-2">
          <input type="submit"  class="btn btn-primary btn-block rounded" value="Search">
        </div>
        <div class="col-lg-12 mb-4 mb-xl-0 col-xl-2"></div>
      </div>            
    </form>
  </div>

templates/furugi/partials/sidebar.html
<div class="col-lg-2 ml-auto">
    <div class="mb-5">
      <h3 class="h5 text-black mb-3">Filters</h3>
      <form action="{% url 'furugi:searching' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <div class="select-wrap">
              <span class="icon"><span class="icon-keyboard_arrow_down"></span></span>
              <select class="form-control" name="category" id="">
              {% if request.session.category != 'None' %}
                <option value="{{ request.session.category }}">{{ request.session.category }}</option>
              {% endif %}
                <option value="None">All Categories</option>
                <option value="Summer Wear">Summer Wear</option>
                <option value="Bridal Wear">Bridal Wear</option>
                <option value="Party Wear">Party Wear</option>
                <option value="Couture">Couture</option>                 
                <option value="Traditional">Traditional</option>
                <option value="Western Wear">Western Wear</option>
                <option value="Sweaters & Jackets">Sweaters & Jackets</option>
                <option value="Pent & Shirt">Pent & Shirts</option>
                <option value="Winter Wear">Winter Wear</option>
                <option value="Night Suits">Night Suits</option>
                <option value="Footwear">Footwear</option>
                <option value="Accessories">Accessories</option>
                <option value="Jewellery">Jewellery</option>
                <option value="Make-up">Make-up</option>
                <option value="Skin & Hair">Skin & Hair</option>
                <option value="Watches">Watches</option>                
              </select>
            </div>
        </div>
        <div class="form-group">
          <div class="select-wrap">
            <span class="icon"><span class="icon-keyboard_arrow_down"></span></span>
            <select class="form-control" name="gender" id="">
            {% if request.session.gender == 'Male' %}                    
              <option value="Male">Male</option>
              <option value="Female">Female</option>  
              <option value="Not Specified">Any</option>
            {% elif request.session.gender == 'Female' %}
              <option value="Female">Female</option>
              <option value="Not Specified">Any</option>
              <option value="Male">Male</option>
            {% else %}
              <option value="Not Specified">Gender</option>
              <option value="Male">Male</option>
              <option value="Female">Female</option> 
            {% endif %}
              
            
            </select>
          </div>
        </div>
        <div class="form-group">
          <p>Max Price: <span id="demo"></span></p>
        </div>
        <div class="form-group">
          <div class="slidecontainer">
            <input type="range" min="1000" max="50000" value="{{ request.session.price }}" class="slider" name="price" id="myRange">
          </div>
        </div>
      
       <input type="submit" class="btn btn-primary btn-block rounded" value="Apply">
      </form>
    </div>
    <div class="mb-5">
      <h3 class="h5 text-black mb-3">Tags </h3>
      <small>(Most common)</small>
      <div>
      {% for tag in tags %}
        <a href="{% url 'furugi:tagged' tag.slug %}" class="mr-1 badge badge-info">{{ tag.name }}</a>
      {% endfor %}
      </div>  
    </div>
    {% include 'furugi/partials/long_ads.html' %}
</div>

   
  

    

templates/furugi/partials/square_ads.html
<div style="background:#F1F6FB;border:#D6DFD8 2px solid;vertical-align:middle;text-align:center;width:260px; height:300px; padding:78px 68px 78px 68px;color:#879F9F">
    <b>Advertise Here</b><br/>Mail Us<br/>
    <span style="font-size:small">contact@furugi.com.pk</span>
</div>