urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'furugi'
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('user-profile', views.user_profile, name="user-profile"),
    path('view-profile', views.view_profile, name="view-profile"),
    path('user-ads', views.user_ads, name="user-ads"),
    path('user-favorites', views.user_favorites, name="user-favorites"),
    path('add-favorites/<int:id>', views.add_user_favorites, name="add-favorites"),
    path('remove-favorites/<int:id>', views.remove_user_favorites, name="remove-favorites"),
    path('ad-create', views.add_advertisment, name="create"),
    path('ad-view/<int:id>/<slug>', views.view_advertisment, name="view"),
    path('ad-edit/<int:id>', views.edit_advertisment, name="edit"),
    path('ad-delete/<int:id>', views.delete_advertisment, name="delete"),   
    path('ad-review', views.add_review, name="ad-review"),   
    path('ads', views.ads, name="ads"),
    path('thread/<int:u_id>/<int:d_id>', views.create_thread, name="thread"),
    path('chatbox', views.chatbox, name="chatbox"),
    path('get-messages', views.get_messages, name="get-messages"),
    path('post-message', views.post_message, name="post-message"),
    path('ads/tag/<slug>', views.filtered_ads, name="tagged"),
    path('report/<int:u_id>/<int:d_id>', views.report_user, name="report"),
    path('block/<id>/', views.block_user, name="block"),
    path('thread/ad-view/<int:id>', views.thread_advertisment),
    path('get-notifications', views.get_notifications, name="get-notifications"),
    path('search-results', views.search_results, name="searching"),
    path('contact', views.contact, name="contact"),
    path('terms-and-conditions', views.terms_and_conditions, name="terms-and-conditions"),
    path('privacy-policy', views.privacy_policy, name="privacy-policy"),
    path('about', views.about, name="about"),
    path('404', views.error_404, name="404"),
    path('admin/user-management', views.user_management , name = 'user-management'),
    path('deactivate-user/<int:id>', views.deactivate_user, name = 'deactivate-user'),
    path('activate-user/<int:id>', views.activate_user, name = 'activate-user'),
    path('admin/user-reporting', views.user_reporting , name = 'user-reporting'),
    path('blog/<slug>', views.blog_view , name = 'blog'),
    path('blogs', views.blogs , name = 'blogs'),
    path('pics/<pic>', views.add_advertisment_pictures , name = 'pics'),
    path('custom/admin', views.admin_dashboard , name = 'custom-admin'),
    path('add-to-cart', views.add_to_cart , name = 'add-to-cart'),
    path('user-cart', views.user_cart , name = 'cart'),
    path('user-orders', views.user_orders , name = 'orders'),
    path('delete-item/<id>', views.delete_item , name = 'delete-item'),
    path('create-order', views.create_order , name = 'order'),
    path('deliver-order/<id>', views.deliver_order , name = 'deliver'),
    path('cancel-order/<id>', views.cancel_order , name = 'cancel'),
    path('delete-order/<id>', views.delete_order , name = 'delete'),
    path('dispatch-order/<id>', views.dispatch_order , name = 'dispatch'),
    path('get-items', views.get_items, name='get-items'),
    path('past-orders', views.past_orders , name = 'past-orders'),
    path('orders-history', views.orders_history , name = 'orders-history'),
    path('get-orders', views.get_orders , name = 'get-orders'),
    path('category/<category>', views.category_results, name="category"),
    path('delete/thread/<id>', views.delete_thread, name="delete-thread"),
    path('sort', views.sort_ads , name = 'sort'),
]

views/advertisment.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from ..models import Dress, Dress_Pictures, Trending, Personal_Details, Favorites, Dress_Rating, Pictures, Thread, Chat, User_Thread, Report, Ad_Thread
from datetime import datetime, date
from django.templatetags.static import static
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from taggit.models import Tag
from django.core.mail import send_mail
from django.db.models import Avg
from django.http import Http404
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from random import randrange

@login_required
def add_advertisment(request):
   
    if request.method == 'POST':       
        user = request.user
        tag_list = []
        files = request.FILES.getlist('pro-image')
        date = request.POST.get('date', False)
        tagsInput = request.POST["tags"]
        tags = tagsInput.strip()
        if tags.startswith(','):
            tags = tags[1:]
        tag_list = iter(tags.split(","))

        if date == '':
            date = None

        profile = files[0]
        try:
            dress = Dress.objects.create(user = user, title = request.POST.get('title'), description = request.POST.get('description'),
            category = request.POST.get('category'), 
            gender = request.POST.get('gender'), quantity = request.POST.get('quantity'), 
            price = request.POST.get('price'), profile = profile)  
        except Dress.DoesNotExist:
            raise Http500()

        for tag in tag_list:   
            dress.tags.add(tag)
    
        dress = Dress.objects.latest('id')  
        for photo in files[1:]:  
            print(photo)            
            Dress_Pictures.objects.create(dress =  dress, file = photo)
        return redirect('/ads')
    else:
        if(request.user.is_active):    
            tags = Dress.tags.most_common()[:8]
            #tags = ["cotton", "embroided", "silk", "chiffon", "khaddar", "mariab", "nishat", "linen", "organza"]
            data = {'tags' : tags}       
            return render(request, 'furugi/advertisment/create.html', data)
        else:            
            return redirect('/login')
            
def add_advertisment_pictures(dress, photo):  
    Dress_Pictures.objects.create(dress =  dress, file = photo) 


def ads(request):
    request.session['category'] = 'None'
    request.session['price'] = 10000
    request.session['gender'] = 'Not Specified'
    try:
        dress = Dress.objects.annotate(stars = Avg('dress_rating__stars')).order_by('-posted_date')   
    except Dress.DoesNotExist:
        raise Http404()
    page = request.GET.get('page', 1)
    paginator = Paginator(dress, 19)
    try:
        dress = paginator.page(page)
    except PageNotAnInteger:
        dress = paginator.page(1)
    except EmptyPage:
        dress = paginator.page(paginator.num_pages)

    tag = Dress.tags.most_common()[:20]
    trending = Trending.objects.all()
    start = randrange(15,25)        
    rated = Dress.objects.annotate(stars = Avg('dress_rating__stars')).order_by('-posted_date')[start:][:11]
      
    data = {"dresses": dress, "tags": tag, 'trending': trending, 'rated': rated }
    return render(request, 'furugi/listings.html', data)

def filtered_ads(request, slug):
    try:    
        dress = Dress.objects.filter(tags__name__in=[slug]).order_by('-posted_date')
    except Dress.DoesNotExist:
        raise Http404()
    page = request.GET.get('page', 1)

    paginator = Paginator(dress, 19)
    try:
        dress = paginator.page(page)
    except PageNotAnInteger:
        dress = paginator.page(1)
    except EmptyPage:
        dress = paginator.page(paginator.num_pages)
     
    tag = Dress.tags.most_common()[:20]
    trending = Trending.objects.all()
    start = randrange(15,25)        
    rated = Dress.objects.annotate(stars = Avg('dress_rating__stars')).order_by('-posted_date')[start:][:11]
      
    data = {"dresses": dress, "tags": tag, 'trending': trending, 'rated': rated}

    return render(request, 'furugi/listings.html', data)

def view_advertisment(request, id, slug):      
    try:
        dressGrp = Dress.objects.filter(id = id).select_related('user') 
    except Dress.DoesNotExist:
        raise Http404("Dress does not exist")
    pics = Dress_Pictures.objects.filter(dress = id)
    reviews = Dress_Rating.objects.filter(dress = id)
    try:
        dress = Dress.objects.get(id = id)
    except Dress.DoesNotExist:
        raise Http404("Dress does not exist")
    tags = dress.tags.all()
    user = dressGrp[0].user
    try:       
        details = Personal_Details.objects.get(user = dressGrp[0].user)
    except:
        details = ''    
    dress.views = dress.views + 1    
    dress.save()
    trending = Trending.objects.all()
    start = randrange(15,25)        
    rated = Dress.objects.annotate(stars = Avg('dress_rating__stars')).order_by('-posted_date')[start:][:11]
    ads = Dress.objects.filter(user = user).order_by('-posted_date')  
    data = {"dress": dressGrp[0], "ads":ads, "pics": pics, "tags":tags, "reviews": reviews, "details": details, "trending":trending, "rated":rated}
    return render(request, 'furugi/advertisment/view.html', data)

@login_required
def edit_advertisment(request, id):
    if request.method == 'POST':
        files = request.FILES.getlist('pro-image', False)     
        available_on = request.POST.get('date')
        tags = request.POST["tags"]        
        dress = Dress.objects.get(id = id)
          
        if available_on == '':
            available_on = dress.available_on
                         
        if files == False:
            profile = dress.profile.name
        else:
            profile = files[0]
    
        try:
            dress = Dress.objects.get(id = id)
            dress.title = request.POST.get('title')
            dress.description = request.POST.get('description')
            dress.category = request.POST.get('category') 
            dress.gender = request.POST.get('gender')
            dress.quantity = request.POST.get('quantity')
            dress.price = request.POST.get('price')
            dress.profile = profile
            dress.save()
        except Dress.DoesNotExist:
            raise Http500()
        if files != False:
            Dress_Pictures.objects.filter(dress = Dress.objects.get(id = id)).delete()           
            for photo in files[1:]:        
                Dress_Pictures.objects.create(dress = Dress.objects.get(id = id) , file = photo)                 
        
        if tags != '':
            dress.tags.clear()
            check = (tags.replace(","," ")) 
            tag_list = iter(check.split(" "))
            for tag in tag_list:   
                dress.tags.add(tag)
            
        messages.add_message(request, messages.SUCCESS, 'Your ad has been updated successfully.')    
        return redirect('/user-ads')
    else:
        dress = Dress.objects.get(id = id)
        pics = Dress_Pictures.objects.filter(dress = id).select_related('dress')
        data = {"dress": dress, "pics": pics}
        return render(request, 'furugi/advertisment/edit.html', data)

@login_required
def delete_advertisment(request, id):      
    try:
        Dress.objects.get(id = id).delete()
    except Dress.DoesNotExist:
        raise Http404()
    messages.add_message(request, messages.ERROR, 'Your ad has been deleted successfully.')    
    return redirect('/user-ads')

@login_required
def add_review(request): 
    name = request.user.username
    review = request.GET.get('review', None)
    stars = request.GET.get('stars', None)
    id = request.GET.get('id', None)
    try:
        save = Dress_Rating.objects.create(dress = Dress.objects.get(id = id),
        stars = stars, review = review, user_name = name )
    except Dress_Rating.DoesNotExist:
        raise Http500()
    try:
        reviews = Dress_Rating.objects.filter(dress = Dress.objects.get(id = id)).values()
    except Dress_Rating.DoesNotExist:
        raise Http404()
    data = { "reviews" : list(reviews)}
    return JsonResponse(data)

def search_results(request):
    gender = request.POST.get('gender')
    title = request.POST.get('title')
    price = request.POST.get('price')
    category = request.POST.get('category')
    request.session['category'] = category
    request.session['price'] = price
    request.session['gender'] = gender
    if title == None:
        if category == 'None' and gender == 'Not Specified':            
            try:
                print('here')
                data = Dress.objects.filter(price__lte = int(price)).order_by('-posted_date')[:22]  
              
            except Dress.DoesNotExist:
                raise Http404()

        elif category == 'None':            
            try:
                print('there')
                #data = Dress.objects.filter(gender = gender, price__lte = int(price)).order_by('-posted_date')[:22]   
                data = Dress.objects.filter(gender = gender, price__lte = int(price)).order_by('-posted_date')[:22]   
                
            except Dress.DoesNotExist:
                raise Http404()

        elif gender == 'Not Specified':            
            try:
                print('mere')
                data = Dress.objects.filter(category = category, price__lte = int(price)).order_by('-posted_date')[:22]   
            
            except Dress.DoesNotExist:
                raise Http404()
        else:           
            try:
                print('chere')

templates/furugi/advertisment/ad_sidebar.html
<style> 
    .list-inline > li{
        margin: 3% 1%;
    }
    .list-inline > li > a
    {
      line-height:25px !important
    } 
</style>
<div class="col-lg-3 ml-auto">
    <div class="mb-5">
        <div class="card bg-light text-dark ">
            <div class="card-header"  style=" background-color:#30e3ca; color: white">
                <h3 class="card-title" style="font-weight:900" >Price: {{dress.price}}</h3>
            </div>
        </div>        
        <div class="card " style="margin-top:10%">
            {% include 'furugi/partials/notification.html' %}
            <div class="card-header"  style=" background-color:#30e3ca; color: white">
                <h2 style="font-weight:900">Advertiser</h2>
            </div>
            <div class="card-body"  >
                <h4 class="card-title">
                    {{dress.user}}
                </h4>
                <p class="card-text">{{details.city}} - {{details.country}}</p>                
                <div><a  href="#profile" data-toggle="modal">View Profile</a></div>
                <a href="#myModal" class="btn btn-primary" data-toggle="modal">Click to Chat</a>   
                </div> 
          </div>
          <div class="card bg-light text-dark " style="margin-top:15%">
            <div class="card-header"  style=" background-color:#30e3ca; color: white">
                <h3 class="card-title" style="font-weight:900" >All Categories</h3>
            </div>
            <div class="card-body">
                <ul class="list-inline">             
                    <li class="list-inline-item" ><a href="{% url 'furugi:category' 'Summer Wear' %}" class="mr-1 badge badge-info" >Summer Wear</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Bridal Wear' %}" class="mr-1 badge badge-info">Bridal Wear</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Party Wear' %}" class="mr-1 badge badge-info">Party Wear</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Couture' %}" class="mr-1 badge badge-info">Couture</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Traditional' %}" class="mr-1 badge badge-info">Traditional</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Western Wear' %}" class="mr-1 badge badge-info">Western Wear</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Sweaters & Jackets' %}" class="mr-1 badge badge-info">Sweaters & Jackets</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Pent & Shirts' %}" class="mr-1 badge badge-info">Pent & Shirts</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Winter Wear' %}" class="mr-1 badge badge-info">Winter Wear</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Night Suits' %}" class="mr-1 badge badge-info">Night Suits</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Footwear' %}" class="mr-1 badge badge-info">Footwear</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Accessories' %}" class="mr-1 badge badge-info">Accessories</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Jewellery' %}" class="mr-1 badge badge-info">Jewellery</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Make-up' %}" class="mr-1 badge badge-info">Make-up</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Skin & Hair' %}" class="mr-1 badge badge-info">Skin & Hair</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Watches' %}" class="mr-1 badge badge-info">Watches</a></li>
                    <li class="list-inline-item"><a href="{% url 'furugi:category' 'Other' %}" class="mr-1 badge badge-info">Other</a></li>               
                  </ul>               
              </div>
        </div>  
    </div>
    <div class="bs-example">
        <div id="myModal" class="modal">
            {% if not user.is_authenticated %}
            <div class="modal-dialog">
                <div class="modal-content"> 
                    <div class="modal-header" style="background-color:gainsboro">
                        <h5 class="modal-title" style="font-weight:bold">Attention</h5>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body" style="text-align:center">
                       <a href="{% url 'furugi:login' %}">Login</a> first to chat 
                    </div>                       
                </div>
            </div>
            {% else %}
            <div class="modal-dialog" id="chat-model">
                <div class="modal-header" style="background-color:#30e3ca; ">
                    <h5 class="modal-title" style="font-weight:bold; color:white">Initialize Chat</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-content" style="border:3px solid white">             
                    <form action="{% url 'furugi:thread' dress.user_id dress.id %}" method="post" enctype="multipart/form-data" >
                        {% csrf_token %}                 
                    <div class="modal-body">
                    <textarea class="form-control" col='5' rows="3" name='msg' placeholder="Type Your Message....."></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Send</a>
                    </div>
                    </form>
                </div>
            </div>
            {% endif %}
        </div>
    </div> 
    {% include 'furugi/partials/square_ads.html' %}
        <span style="margin:1%"></span>
    {% include 'furugi/partials/square_ads.html' %}
</div>
{% include 'furugi/account/full_profile.html' %}
{% include 'furugi/account/report.html' %}

templates/furugi/advertisment/add_review.html
<div class="container">
    <div class="row" style="margin-top:60px;">
      <div class="col-md-12">
              <div class="text-right">
                  <button class="btn btn-success btn-green" data-toggle="collapse" data-target="#review" >Leave a Review</button>
              </div>                  
              <div class="collapse" id="review" style="margin:20px; padding:10px; border: 1px solid black; border-radius:5px" >
    
                <div class="col-md-12" >    
                  {% if not user.is_authenticated %}
                  <small style="color:Red;  font-weight:bold">Kindly login first otherwise your comment won't be posted</small>
                  {% endif %}
                
                          <textarea class="form-control animated" cols="50" id="comment" placeholder="Enter your review here..." rows="3" maxlength="10000"></textarea>  
                          <div class="text-right">   
                            <div class="row" style="margin-top:10px; margin-bottom:10px">
                              <div class="col-md-9">
                                <strong >Stars </strong> (upto 5)
                              </div>
                              <div class="col-md-3">                                                                    
                                <input type="number" class="form-control" id="stars" max="5" value="5">
                              </div>
                            </div> 
                          </div>
                          <button  class="btn btn-primary btn-lg btn-block" id="post-review" data-id={{dress.id}} style="background-color: #30e3ca; border: #30e3ca">Post</button>
                  </div>                 
              </div>                   
      </div>
    </div>
  </div>
  {% load static %}
  <script src="{% static 'furugi/js/review.js' %}"></script>

templates/furugi/advertisment/rating.html
<p class="mb-0">
  {% if data.stars >= 4.5 or data.stars == None%}
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  {% elif  data.stars >= 3.5 and data.stars < 4.5 %}
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-secondary"></span>
  {% elif  data.stars >= 2.5 and data.stars < 3.5 %}
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-secondary"></span>
  <span class="icon-star text-secondary"></span>
  {% elif  data.stars >= 1.5 and data.stars < 2.5 %}
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-secondary"></span>
  <span class="icon-star text-secondary"></span>
  <span class="icon-star text-secondary"></span>
  {% elif  data.stars < 1.5 %}
  <span class="icon-star text-warning"></span>
  <span class="icon-star text-secondary"></span>
  <span class="icon-star text-secondary"></span>
  <span class="icon-star text-secondary"></span>
  <span class="icon-star text-secondary"></span>

  {% endif %}
</p>

templates/furugi/advertisment/reviews.html
<div class="site-section bg-light" >
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-7 text-left border-primary">
          <h2 class="font-weight-light text-primary">Reviews</h2>
        </div>
      </div>
   
      <div id="reviews">
        {% if not reviews  %}
            <mark>No Reviews Yet</mark>
        {% endif %}
       {% for data in reviews %}

        <div class="col-lg-12">
          <div class="d-block d-md-flex listing">   
            <div class="lh-content">                       
              <div class="row">
                <div class="col-md-4">
                  <h3><a href="">{{data.user_name}}</a></h3>
                </div>
                <div class="col-md-8" style="text-align: right;"><span class="category" style="align-text:left;">{{data.rating_date}}</span></div>
              </div>
              <div>{{data.review}}</div>
              {% include 'furugi/advertisment/rating.html' %}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

templates/furugi/advertisment/view.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}
{% load static %}
{% include 'furugi/partials/mobile_menu.html' %}
    <div class="site-blocks-cover inner-page-cover overlay" style="background-image: url({{dress.profile.url}});" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">
          <div class="col-md-10" data-aos="fade-up" data-aos-delay="400"> 
            <div class="row justify-content-center mt-5">
              <div class="col-md-8 text-center">
                <h1>{{dress.title}}</h1>               
              </div>
            </div>           
          </div>
        </div>
      </div>
    </div> 

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">            
            <div class="mb-4">
              <div class="slide-one-item home-slider owl-carousel">
                <div><img src="{{dress.profile.url}}" alt="Image" class="img-fluid"></div>
                {% for pic in pics %}    
                <div><img src="{{pic.file.url}}" alt="Image" class="img-fluid"></div>
                {% endfor %}                                
              </div>
            </div>
          {% if dress.description %}   
           <h4 class="h5 mb-4 text-black">Description</h4>
           <p> {{dress.description}}</p>
          {% endif %}   
          {% for tag in tags %}
          <a href="{% url 'furugi:tagged' tag.slug %}" class="mr-1 badge badge-info">{{ tag }}</a>
        {% endfor %} 
      
         <div class="row">      
          <div class="col-sm-2 col-md-2 col-5">
              <label style="font-weight:bold;">Size Chart</label>
          </div>
          <div class="col-md-4 col-6" >
            <a href="{% static 'furugi/images/size_chart.jpg' %}">Click to view</a>
          </div>         
         </div>
         <div class="row">
          <div class="col-sm-2 col-md-2 col-5">
              <label style="font-weight:bold;">Category</label>
          </div>
          <div class="col-md-4 col-6" >
            {{dress.category}}
          </div>    
          <div class="col-sm-2 col-md-2 col-5">
            <h4 style="font-weight:bold; "> Price:</h4>
          </div>
          <div class="col-md-4 col-6" >
            <h4>{{dress.price}} </h4>
          </div>            
       </div>
                 
           {% if dress.quantity > 0 %}
          <div class="row" style="float:right; color:white; margin:2%">
            <a class="btn btn-warning" id="add-to-cart" data-id="{{dress.id}}">Add To Cart</a>           
          </div> 
          {% else %}
          <div class="row" style="float:right; color:red; background-color:beige; margin:2%; padding:1%">
            Out Of Stock          
          </div> 
          {% endif %}
              
          <div class="row" style="float:center">
             <p class="order-text" style="font-weight:bold; color:navy; background-color:aquamarine"></p>
          </div>
          
       
          {% include 'furugi/advertisment/add_review.html' %}
          {% include 'furugi/advertisment/reviews.html' %}
        </div>

          {% include 'furugi/advertisment/ad_sidebar.html' %}
      
        </div>
      </div>
    </div>
    {% if ads.count > 1 %}
    <div class="container" style="margin-bottom:5%">
      <div class="row mb-5">
        <div class="col-md-7 text-left border-primary">
          <h2 class="font-weight-light text-primary">Other Ads From Same Advertiser</h2>
        </div>
      </div>
      <div class="col-12  block-13">
        <div class="owl-carousel nonloop-block-13">   
        {% for data in ads %}             
          <div class="d-block d-md-flex listing vertical">
            <a href="{% url 'furugi:view' data.id data.slug %}" class="img d-block" style="background-image: url( '{{ data.profile.url}}')"></a>
            <div class="lh-content">
              <span class="category">{{data.category}}</span>
              <a href="{% url 'furugi:add-favorites' data.id %}" class="bookmark" data-toggle="tooltip" title="Add to favorites"><span class="icon-heart" ></span></a>
              <h3><a href="{% url 'furugi:view' data.id data.slug %}">{{ data.title}}</a></h3>
            
              <strong>Price: {{ data.price}}</strong>
              <span class="review" style="float:right"><em><small> ({{ data.views}} Views)</small></em></span>                
              <div>                           
                {% for tag in data.tags.all|slice:':2' %}
                   <a href="{% url 'furugi:tagged' tag.slug %}" class="mr-1 badge badge-info">{{ tag.name }}</a>
                {% endfor %}
              </div>             
            </div>  
          </div>
        {% endfor %}
        </div>
      </div>
    </div> 
    {% endif %}
    {% include 'furugi/partials/banner.html' %}
     {% include 'furugi/partials/trending.html' %}
    {% include 'furugi/partials/testimonials.html' %}  
  
 {% endblock %}   
    
 