urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'furugi'
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('user-profile', views.user_profile, name="user-profile"),
    path('view-profile', views.view_profile, name="view-profile"),
    path('user-ads', views.user_ads, name="user-ads"),
    path('user-favorites', views.user_favorites, name="user-favorites"),
    path('add-favorites/<int:id>', views.add_user_favorites, name="add-favorites"),
    path('remove-favorites/<int:id>', views.remove_user_favorites, name="remove-favorites"),
    path('ad-create', views.add_advertisment, name="create"),
    path('ad-view/<int:id>/<slug>', views.view_advertisment, name="view"),
    path('ad-edit/<int:id>', views.edit_advertisment, name="edit"),
    path('ad-delete/<int:id>', views.delete_advertisment, name="delete"),   
    path('ad-review', views.add_review, name="ad-review"),   
    path('ads', views.ads, name="ads"),
    path('thread/<int:u_id>/<int:d_id>', views.create_thread, name="thread"),
    path('chatbox', views.chatbox, name="chatbox"),
    path('get-messages', views.get_messages, name="get-messages"),
    path('post-message', views.post_message, name="post-message"),
    path('ads/tag/<slug>', views.filtered_ads, name="tagged"),
    path('report/<int:u_id>/<int:d_id>', views.report_user, name="report"),
    path('block/<id>/', views.block_user, name="block"),
    path('thread/ad-view/<int:id>', views.thread_advertisment),
    path('get-notifications', views.get_notifications, name="get-notifications"),
    path('search-results', views.search_results, name="searching"),
    path('contact', views.contact, name="contact"),
    path('terms-and-conditions', views.terms_and_conditions, name="terms-and-conditions"),
    path('privacy-policy', views.privacy_policy, name="privacy-policy"),
    path('about', views.about, name="about"),
    path('404', views.error_404, name="404"),
    path('admin/user-management', views.user_management , name = 'user-management'),
    path('deactivate-user/<int:id>', views.deactivate_user, name = 'deactivate-user'),
    path('activate-user/<int:id>', views.activate_user, name = 'activate-user'),
    path('admin/user-reporting', views.user_reporting , name = 'user-reporting'),
    path('blog/<slug>', views.blog_view , name = 'blog'),
    path('blogs', views.blogs , name = 'blogs'),
    path('pics/<pic>', views.add_advertisment_pictures , name = 'pics'),
    path('custom/admin', views.admin_dashboard , name = 'custom-admin'),
    path('add-to-cart', views.add_to_cart , name = 'add-to-cart'),
    path('user-cart', views.user_cart , name = 'cart'),
    path('user-orders', views.user_orders , name = 'orders'),
    path('delete-item/<id>', views.delete_item , name = 'delete-item'),
    path('create-order', views.create_order , name = 'order'),
    path('deliver-order/<id>', views.deliver_order , name = 'deliver'),
    path('cancel-order/<id>', views.cancel_order , name = 'cancel'),
    path('delete-order/<id>', views.delete_order , name = 'delete'),
    path('dispatch-order/<id>', views.dispatch_order , name = 'dispatch'),
    path('get-items', views.get_items, name='get-items'),
    path('past-orders', views.past_orders , name = 'past-orders'),
    path('orders-history', views.orders_history , name = 'orders-history'),
    path('get-orders', views.get_orders , name = 'get-orders'),
    path('category/<category>', views.category_results, name="category"),
    path('delete/thread/<id>', views.delete_thread, name="delete-thread"),
    path('sort', views.sort_ads , name = 'sort'),
]

views/chatbox.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from ..models import Dress, Dress_Pictures, Personal_Details, Favorites, Dress_Rating, Thread, Chat, User_Thread,Report, Ad_Thread, Block
from datetime import datetime, date
from django.templatetags.static import static
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from taggit.models import Tag
from django.core.mail import send_mail
from django.db.models import Avg
from django.http import Http404
from django.contrib.postgres.search import TrigramSimilarity
from django.db.models.functions import Greatest
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from twilio.rest import Client

@login_required
def chatbox(request):       
    user_thread = User_Thread.objects.filter(sender = request.user).order_by('-thread') 
    thread = list(user_thread)
    chat = []    
    for user in user_thread:
        data = Chat.objects.filter(thread = user.thread, user= user.reciever, read = 0).count()
        chat.append(data)
    data = {'data' : zip(chat,thread)}
    return render(request, 'furugi/chatbox.html', data)

@login_required
def create_thread(request, u_id, d_id):
    user = request.user
    dress = Dress.objects.get(id = d_id)
    reciever = User.objects.get(id = u_id) 
    if user == reciever:
        messages.add_message(request, messages.ERROR, 'Your cannot message yourself on your own Ads.')    
        return redirect('/user-ads')
    block = Block.objects.filter(user = user, reporter = reciever).count()
    if block > 0:
        messages.add_message(request, messages.ERROR, 'Respective advertiser has blocked you. So you cannot chat with them anymore.')    
        return redirect('/ads')
    Thread.objects.create()
    thread = Thread.objects.latest('id')    
    email = str(reciever.email)
    
    try:    
        User_Thread.objects.create(thread = thread, sender = user, reciever = reciever )
    except User_Thread.DoesNotExist:
        raise Http500()
    try:    
        User_Thread.objects.create(thread = thread, sender = User.objects.get(id = u_id), reciever = user )
    except User_Thread.DoesNotExist:
        raise Http500()
    try:    
        Chat.objects.create(thread = thread, message = request.POST.get('msg'), user = request.user )
    except Chat.DoesNotExist:
        raise Http500()
    try:    
        Ad_Thread.objects.create(thread = thread, dress = dress)
    except Ad_Thread.DoesNotExist:
        raise Http500()
    chat_notification(request, email)
    try:
        profile = Personal_Details.objects.get(user = reciever)
        if not profile:
            contact = ''
        else:
            contact = str(profile.contact)
            #sendMsg(request, contact)
    except Exception as e:
        pass
    return redirect('/chatbox')

@login_required
def delete_thread(request, id):
    try:
        Thread.objects.get(id = id).delete()
    except Exception as e:
        pass
    return redirect('/chatbox')

@login_required
def get_messages(request):
    id = request.GET.get('id', None)
    thread = Thread.objects.get(id = id)
    ad = Ad_Thread.objects.filter(thread = thread)
    dress = Dress.objects.filter(id = ad[0].dress.id).values()
    data = Chat.objects.filter(thread = thread).order_by('timestamp') 
    chat = data.values()
    data.exclude(user = request.user).update(read = 1)    
    data = {'chat': list(chat), 'ad': list(dress)}
    return JsonResponse(data)

@login_required
def post_message(request):
    id = request.GET.get('id', None)
    msg = request.GET.get('msg', None)
    try:
        c = Chat.objects.create(thread =  Thread.objects.get(id=id), message = msg, user = request.user )
    except Chat.DoesNotExist:
        raise Http500()
    data = {'message': msg, 'thread_id': id, 'timestamp': c.timestamp}
    return JsonResponse(data)

@login_required
def thread_advertisment(request, id):
    thread = Thread.objects.get(id = id)
    ad = Ad_Thread.objects.get(thread = thread)
    id = ad.dress.id
    return redirect('/ad-view/'+ id)

@login_required
def chat_notification(request, email):
    subject = "New Message Notification"
    html_message = render_to_string('partials/email.html', {'context': 'values'})
    plain_message = strip_tags(html_message)
    send_mail(subject, plain_message, 'CHAT NOTIFICATION <contact@furugi.com.pk>',[email], html_message= html_message)
 
@login_required
def sendMsg( request, number):
    account_sid = "AC733c99c53e17dc55c875fec65b77888c"
    auth_token  = "e28847557e7008dab4a2f8b7702f8138"
    client = Client(account_sid, auth_token)

    if number.startswith('0'):
        x = number
        remove = x[1:]
        number = '+92'+remove
    try:    
        message = client.messages.create(
        body="Dear costumer,\n You have recieved new message thread at FURUGI. Visit 'Chatbox' section on website now and respond well to your costumers.\n Regards, FURUGI Team",
        to= number,
        from_="+16105467688")
    except Exception as e:
       pass

views/order.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from ..models import Dress, Personal_Details, Cart, Order
from datetime import datetime, date
from django.templatetags.static import static
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from taggit.models import Tag
from django.core.mail import send_mail
from django.http import Http404
from django.contrib.auth.decorators import login_required
from twilio.rest import Client
from django.template.loader import render_to_string
from django.utils.html import strip_tags


@login_required
def delete_item(request, id):  
    dress = Dress.objects.get(id =id)  
    user = request.user  
    try:
        Cart.objects.get(user = user , dress = dress).delete()
    except Cart.DoesNotExist:
        raise Http404()
    messages.add_message(request, messages.ERROR, 'Item Removed')    
    return redirect('/user-cart')

@login_required
def create_order(request): 
    user = request.user 
    contact = request.POST.get("contact")
    address = request.POST.get("address")
    
    cart = Cart.objects.filter(user = user)  

    for c in cart: 
        try:
            Order.objects.create(dress = c.dress , contact = contact, street = address, responsible = c.dress.user, reciever = user )
            dress = Dress.objects.get(id = c.dress.id)
            dress.quantity = dress.quantity - 1
            dress.save()
            try:
                profile = Personal_Details.objects.get(user = c.dress.user)
                if not profile:
                    number = ''
                else:
                    number = str(profile.contact)
                    sendMsg(request, number)    
            except Exception as e:
                pass              
            email = c.dress.user.email    
            order_notification(request, email)
        except Order.DoesNotExist:
            raise Http404()
    Cart.objects.filter(user = user).delete()
  
    messages.add_message(request, messages.SUCCESS, 'Order successfully placed ! It will be delivered within a week. Keep a check on your email and mobile. Go and Shop more.')    
    return redirect('/past-orders')

@login_required
def user_orders(request):    
    user = request.user
    try:
        data = Order.objects.filter(responsible = user, delivered = 0).select_related('dress').order_by('-date')
    except Order.DoesNotExist:
        raise Http404()
    
    data = {"orders": data}
    return render(request, 'furugi/orders.html', data)

@login_required
def deliver_order(request, id):  
    order = Order.objects.get(id =id)  
    order.delivered = 1
    order.date_delivered = datetime.now()
    order.save()
    return redirect('/user-orders')

@login_required
def cancel_order(request, id):  
    order = Order.objects.get(id =id)  
    order.cancelled = 1
    order.save()
    return redirect('/past-orders')

@login_required
def dispatch_order(request, id):  
    order = Order.objects.get(id =id)  
    order.dispatched = 1
    order.save()
    return redirect('/user-orders')

@login_required
def delete_order(request, id):  
    order = Order.objects.get(id =id).delete()  
    return redirect('/user-orders')

@login_required
def get_items(request):
    user = request.user
    items = Cart.objects.filter(user = user).count()
    data = { "items" : items}
    return JsonResponse(data)

@login_required
def past_orders(request):    
    user = request.user
    try:
        data1 = Order.objects.filter(reciever = user, delivered = 0, cancelled = 0).select_related('dress').select_related('responsible').order_by('-date')
        data2 = Order.objects.filter(reciever = user, delivered = 1, cancelled = 0).select_related('dress').select_related('responsible').order_by('-date')
    except Order.DoesNotExist:
        raise Http404()    
    data = {"ordersND": data1, "ordersD": data2}
    return render(request, 'furugi/account/past_orders.html', data)

@login_required
def sendMsg( request, number):
    account_sid = "AC733c99c53e17dc55c875fec65b77888c"
    auth_token  = "e28847557e7008dab4a2f8b7702f8138"
    client = Client(account_sid, auth_token)

    if number.startswith('0'):
        x = number
        remove = x[1:]
        number = '+92'+remove
    try:    
        message = client.messages.create(
        body="Dear costumer,\n You have recieved new order at FURUGI. Visit 'Orders' section on website now and make sure to fulfill that order within two days as delaying in delivery might restrict your access from FURUGI.\n Regards, FURUGI Team",
        to= number,
        from_="+16105467688")
    except Exception as e:
       pass
    
@login_required
def orders_history(request):    
    user = request.user
    try:
        data = Order.objects.filter(responsible = user, delivered = 1).select_related('dress').order_by('-date')
    
    except Order.DoesNotExist:
        raise Http404()
    
    data = {"orders": data}
    return render(request, 'furugi/orders_history.html', data)

@login_required
def get_orders(request):    
    user = request.user
    try:
        data = Order.objects.filter(responsible = user, delivered = 0).count()
    
    except Order.DoesNotExist:
        raise Http404()
    
    data = {"orders": data}
    return JsonResponse(data)

@login_required
def order_notification(request , email):
    print('email-recived = '+ email)
    subject = "New Order Notification"
    html_message = render_to_string('furugi/emails/order_notification.html', {'context': 'values'})
    plain_message = strip_tags(html_message)
    send_mail(subject, plain_message, 'ORDER NOTIFICATION <contact@furugi.com.pk>',[email], html_message=html_message)

templates/furugi/index.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}
{% load static %}

<style>

  @media screen and (max-width: 600px) {
    #hide {display:none;} 
    #latest {margin-top: 15%;}
  }

  .mr-1 badge badge-info 
  {
    line-height:25px !important
  } 
</style>

  <div class="site-wrap">
    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    <div class="site-blocks-cover overlay" style="background-image: url('{% static 'furugi/images/buy-clothes-online-in-pakistan.jpeg' %}')" alt="A beautiful girl in silk dress" data-aos="fade" data-stellar-background-ratio="0.5">
      
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">
          <div class="col-md-12">
            <div class="row justify-content-center mb-4">
              <div class="col-md-8 text-center">
                <h1 class="" data-aos="fade-up">Largest Fashion Classifieds In Pakistan</h1>
                <p data-aos="fade-up" data-aos-delay="100">You can buy, sell and rent out clothing wears from anywhere to everywhere online in Pakistan</p>
              </div>
            </div>
            {% include 'furugi/partials/search.html' %}
          </div>
        </div>
      </div>
    </div>
    
    <div class="site-section bg-light">    
      <div class="container">  
        <div style='margin-bottom:5%' > {% include 'furugi/partials/latest.html' %} </div>
  
        <div class="border p-3 rounded mb-2" style="background-color:white; color:#30e3ca;  text-align:justify" id="latest">
          <div class="row mb-5">
            <div class="col-md-12 text-center border-primary">
              <h2 class="font-weight-light text-primary">Explore Now</h2>
            </div>
        </div>
      
          <div style="text-align:center">     
           
            <ul class="list-inline">             
              <li class="list-inline-item" ><a href="{% url 'furugi:category' 'Summer Wear' %}" class="mr-1 badge badge-info" >Summer Wear</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Bridal Wear' %}" class="mr-1 badge badge-info">Bridal Wear</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Party Wear' %}" class="mr-1 badge badge-info">Party Wear</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Couture' %}" class="mr-1 badge badge-info">Couture</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Traditional' %}" class="mr-1 badge badge-info">Traditional</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Western Wear' %}" class="mr-1 badge badge-info">Western Wear</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Sweaters & Jackets' %}" class="mr-1 badge badge-info">Sweaters & Jackets</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Pants & Shirts' %}" class="mr-1 badge badge-info">Pants & Shirts</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Winter Wear' %}" class="mr-1 badge badge-info">Winter Wear</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Night Suits' %}" class="mr-1 badge badge-info">Night Suits</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Footwear' %}" class="mr-1 badge badge-info">Footwear</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Accessories' %}" class="mr-1 badge badge-info">Accessories</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Jewellery' %}" class="mr-1 badge badge-info">Jewellery</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Make-up' %}" class="mr-1 badge badge-info">Make-up</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Skin & Hair' %}" class="mr-1 badge badge-info">Skin & Hair</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Watches' %}" class="mr-1 badge badge-info">Watches</a></li>
              <li class="list-inline-item"><a href="{% url 'furugi:category' 'Other' %}" class="mr-1 badge badge-info">Other</a></li>
            
            </ul>
          </div>         
        </div> 
        {% include 'furugi/partials/rectangle_ads.html' %}
        </div>
    </div>
    <div class="col-12 text-center mt-4" style=" background-color: #1cd1b7; padding:5%">
      <p style="color:white"> <span id="hide">Furugi is a classified ads website specifically focused on promoting fashion business. Sell or Buy fashion wears online in Pakistan for the first time right from home. 
         Now you don't have to rush on multiple platforms, you can do online shopping in Pakistan from one single platform.
        </span> <h3 style="color:white; font-weight:bolder">Buy, sell and rent out your used or new fashion wears online absolutely free</h3> 
     
       </p>
       <a href="{% url 'furugi:ads' %}" class="btn btn-primary rounded py-2 px-4 " 
       style="background-color:white; font-weight: bold; color: #1cd1b7">
         View All Ads</a>
     </div>
    {% include 'furugi/partials/popular.html' %}
  
    <div class="col-12 text-center mt-4" style="margin-bottom: 2%;">
      <p style="padding-right:5%; padding-left:5%;  font-weight:bolder;">
        <h4 style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif"> "Furugi is the best place to start a fully functional business of fashion wears for free"
      </h4></p>
      <a href="{% url 'furugi:create' %}" class="btn btn-primary rounded py-2 px-4 text-white"  >
        Post Ad+</a>
    </div>
    {% include 'furugi/partials/rectangle_ads.html' %}
    {% include 'furugi/partials/trending.html' %}
    <div class="col-12 text-center mt-4" style=" background-color: #1cd1b7; padding:5%">
      <h3 style="color:white; font-weight:bolder">Our goal is to enable anyone who wants to do fashion business online for free</h3> 
       <a href="{% url 'furugi:ads' %}" class="btn btn-primary rounded py-2 px-4 " 
       style="background-color:white; font-weight: bold; color: #1cd1b7">
         View All Ads</a>
     </div>
    {% include 'furugi/partials/testimonials.html' %}
    {% include 'furugi/partials/blog.html' %}
  </div>
{% endblock %}

templates/furugi/listings.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}  
{% load static %}
{% include 'furugi/partials/mobile_menu.html' %}
<div class="site-blocks-cover overlay" style="background-image: url('{% static 'furugi/images/online-clothing-market-in-pakistan.jpeg' %}')" alt="A beautiful girl in blue dress" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-12">
        <div class="row justify-content-center mb-4">
          <div class="col-md-8 text-center">
            <h1 class="" data-aos="fade-up">Choose what you'd love</h1>
            <p data-aos="fade-up" data-aos-delay="100">Buy clothes in Pakistan from anywhere and sell to everywhere online in Pakistan</p>
          </div>
        </div>
        {% include 'furugi/partials/search.html' %}
      </div>
    </div>
  </div>
</div>
    <div class="site-section" >
      <div class="container">     
        <form action="{% url 'furugi:sort' %}" method="post">
          {% csrf_token %}
          <div class="row">          
            <div class="col-sm-2">
              <div class="form-group">
                <div class="select-wrap">
                  <span class="icon"><span class="icon-keyboard_arrow_down"></span></span>
                  <select class="form-control" name="sort">   
                    <option value="Newest">Sort by</option>                
                    <option value="Newest">Newest</option>
                    <option value="Oldest">Oldest</option>  
                  </select>
                </div>
              </div>  
            </div>          
            <div class="col-sm-1">        
              <input type="submit" class="btn btn-primary" style="border-radius:4px" value="Go">
            </div>
          </div>
        </form>
      
        <div class="row">
          <div class="col-lg-10">         
              {% include 'furugi/partials/notification.html' %}
            <div class="row">  
              {% if not dresses %}
               <h2><mark>Poo! No results. Try out some other filters</mark></h2>
              {% else %}
              {% for data in dresses %}                
                  <div class="col-lg-3" >                
                    <div class="d-block d-md-flex listing vertical">
                      <a href="{% url 'furugi:view' data.id data.slug %}" class="img d-block" style="background-image: url( '{{ data.profile.url}}')"></a>
                  
                      <div class="lh-content">
                        <span class="category">  {{ data.category}}</span>
                        <a href="{% url 'furugi:add-favorites' data.id %}" class="bookmark" data-toggle="tooltip" title="Add to favorites"><span class="icon-heart" ></span></a>
                        <h3><a href="{% url 'furugi:view' data.id data.slug %}">{{ data.title}}</a></h3>
                        {% if data.description == '' %}
                        <address> (no description) </address>
                        {% else %}
                        <address> {{ data.description}} </address>       
                        {% endif %}        
                                      
                        {% include 'furugi/advertisment/rating.html' %}    
                          <strong>Price: {{ data.price}}</strong>
                          <span class="review" style="float:right"><em><small> ({{ data.views}} Views)</small></em></span>   
                          <div>  
                            {% for tag in data.tags.all|slice:':2' %}
                                 <a href="{% url 'furugi:tagged' tag.slug %}" class="mr-1 badge badge-info">{{ tag.name }}</a>
                            {% endfor %}                           
                          </div>       
                        </div>
                      {% block extra_content %} 
                      {% endblock %}
                    </div>    
                  </div>
                  {% if forloop.counter == 6 %}
                  <div class="col-lg-3">
                    <div class="d-block d-md-flex listing vertical" style="background-color:#F1F6FB;border:#D6DFD8; height:420px">
                      <div class="lh-content" style="text-align:center; color:#879F9F; padding-top:70%">          
                      <h4><b>Advertise Here</b></h4>                    
                      
                      <a href="{% url 'furugi:contact' %}" class="btn btn-info" style="color:white; border-color:grey; ">Contact Us</a>
                      </div>
                    </div>
                  </div>
                  {% endif %}
                  {% if forloop.counter == 14 %}
                  <div class="col-lg-3">
                    <div class="d-block d-md-flex listing vertical" style="background-color:#1cd1b7; height:430px">
                      <div class="lh-content" style="text-align:center; color:white; padding:20%">          
                      <h4><b>Post Your Ad Here For Free</b></h4>
                      <p> Spread your business online, and reach to costumers at large</p>
                      <a href="{% url 'furugi:create' %}" class="btn btn-outline-info" style="color:white; border-color:white; ">Post Ad+</a>
                      </div>
                    </div>
                  </div>
                  {% endif %}
              {% endfor %}
              {% endif %}
            </div>
            {% include 'furugi/partials/pagination.html' %}
        </div>
          {% include 'furugi/partials/sidebar.html' %}     
        </div>
      </div>
    </div>
    {% include 'furugi/partials/trending.html' %}
    {% include 'furugi/partials/testimonials.html' %}      

{% endblock %}

templates/furugi/orders.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}
{% load static %}
{% include 'furugi/partials/mobile_menu.html' %}
<link rel="stylesheet" href=https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css>
<style>
  @media screen and (max-width: 600px) {
    .top {padding-top: 20%;}
  }
</style>
<div class="site-section bg-light" style=" margin-top:10%">
  <div style="background:#F1F6FB;border:#D6DFD8 2px solid;color:#879F9F; margin-top:10%; font-size: 14px; height: 100px; width: 630px; margin-right:20%; margin-left:25%">
    <marquee behavior="alternate" direction="left" scrollamount="2"><span style="float: left; font-family: Oswald, Arial; padding: 0 0 0 2px;">See your Ad here. Email at contact@furugi.com.pk </span></marquee>
  </div>
    <div class="container" style="padding-right:15%;padding-left:15%">
 
      {% if not orders  %}
      <div style="margin-top:5%; padding:20%; font-weight:bold">
        <h2 ><b>No Orders Yet, Put Some Amazing Stuff On FURUGI To Get Orders</b></h2>
        <a href="{% url 'furugi:create' %}" class="btn btn-info"> Post Ad+</a>  
      </div>
      {% else %}
        
      <div class="top" class="row mb-5" style="margin-top:7%;" >
          <div class="col-md-12 text-center border-primary" >
            <h2 class="font-weight-light text-primary">New Orders</h2>
            <p>Make sure to mark orders "Delivered" after delivery</p>
          </div>
      </div>
      {% include 'furugi/partials/notification.html' %}
        <div>          
           {% for data in orders %}
    
           <div class="col-lg-12">
            <div class="d-block d-md-flex listing">
              <a href="{% url 'furugi:view' data.dress.id data.dress.slug %}" class="img d-block" style="background-image: url( '{{ data.dress.profile.url}}')"></a>
              <div class="lh-content">             
                <h3><a href="{% url 'furugi:view' data.dress.id data.dress.slug %}">{{ data.dress.title}}</a></h3>               
                <strong>Price:</strong> {{ data.dress.price}}
                <div><strong>Date Ordered:</strong> {{ data.date}}</div>
                <div><strong>Order by:</strong> {{ data.reciever}}</div>
                <div><strong>Contact:</strong> {{ data.contact}}</div>
                <div><strong>Address:</strong> {{ data.street}}</div>
                <div style="float:right; margin-top:5%">
                  {% if data.cancelled == 1%}
                    <a style="color:maroon">Cancelled by costumer, click 'Noted' to dismiss</a> <a href="{% url 'furugi:delete' data.id %}" class="btn btn-outline-danger btn-sm" >Noted </a>
            
                  {% else %}
                      {% if data.dispatched == 0 %}
                          <a href="{% url 'furugi:dispatch' data.id %}" class="btn btn-outline-success btn-sm" >Dispatch </a>
                      {% else %}
                          <a style="color:darkorange">Dispatched</a>
                      {% endif %}
                      <span>  </span><a href="{% url 'furugi:deliver' data.id %}" class="btn btn-outline-danger btn-sm ">Deliver </a></div>          
                  {% endif %}
                </div>
            </div>
          </div>
            {% endfor %}
        </div>
        {% endif %}
        <div style="text-align:center" ><a href="{% url 'furugi:orders-history' %}" class="btn btn-default" style="width:70%; color:white; background-color:teal">Orders History</a></div>
    </div>
</div>

         
 {% endblock %}   
    
 