urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'furugi'
urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('login', views.user_login, name="login"),
    path('logout', views.user_logout, name="logout"),
    path('user-profile', views.user_profile, name="user-profile"),
    path('view-profile', views.view_profile, name="view-profile"),
    path('user-ads', views.user_ads, name="user-ads"),
    path('user-favorites', views.user_favorites, name="user-favorites"),
    path('add-favorites/<int:id>', views.add_user_favorites, name="add-favorites"),
    path('remove-favorites/<int:id>', views.remove_user_favorites, name="remove-favorites"),
    path('ad-create', views.add_advertisment, name="create"),
    path('ad-view/<int:id>/<slug>', views.view_advertisment, name="view"),
    path('ad-edit/<int:id>', views.edit_advertisment, name="edit"),
    path('ad-delete/<int:id>', views.delete_advertisment, name="delete"),   
    path('ad-review', views.add_review, name="ad-review"),   
    path('ads', views.ads, name="ads"),
    path('thread/<int:u_id>/<int:d_id>', views.create_thread, name="thread"),
    path('chatbox', views.chatbox, name="chatbox"),
    path('get-messages', views.get_messages, name="get-messages"),
    path('post-message', views.post_message, name="post-message"),
    path('ads/tag/<slug>', views.filtered_ads, name="tagged"),
    path('report/<int:u_id>/<int:d_id>', views.report_user, name="report"),
    path('block/<id>/', views.block_user, name="block"),
    path('thread/ad-view/<int:id>', views.thread_advertisment),
    path('get-notifications', views.get_notifications, name="get-notifications"),
    path('search-results', views.search_results, name="searching"),
    path('contact', views.contact, name="contact"),
    path('terms-and-conditions', views.terms_and_conditions, name="terms-and-conditions"),
    path('privacy-policy', views.privacy_policy, name="privacy-policy"),
    path('about', views.about, name="about"),
    path('404', views.error_404, name="404"),
    path('admin/user-management', views.user_management , name = 'user-management'),
    path('deactivate-user/<int:id>', views.deactivate_user, name = 'deactivate-user'),
    path('activate-user/<int:id>', views.activate_user, name = 'activate-user'),
    path('admin/user-reporting', views.user_reporting , name = 'user-reporting'),
    path('blog/<slug>', views.blog_view , name = 'blog'),
    path('blogs', views.blogs , name = 'blogs'),
    path('pics/<pic>', views.add_advertisment_pictures , name = 'pics'),
    path('custom/admin', views.admin_dashboard , name = 'custom-admin'),
    path('add-to-cart', views.add_to_cart , name = 'add-to-cart'),
    path('user-cart', views.user_cart , name = 'cart'),
    path('user-orders', views.user_orders , name = 'orders'),
    path('delete-item/<id>', views.delete_item , name = 'delete-item'),
    path('create-order', views.create_order , name = 'order'),
    path('deliver-order/<id>', views.deliver_order , name = 'deliver'),
    path('cancel-order/<id>', views.cancel_order , name = 'cancel'),
    path('delete-order/<id>', views.delete_order , name = 'delete'),
    path('dispatch-order/<id>', views.dispatch_order , name = 'dispatch'),
    path('get-items', views.get_items, name='get-items'),
    path('past-orders', views.past_orders , name = 'past-orders'),
    path('orders-history', views.orders_history , name = 'orders-history'),
    path('get-orders', views.get_orders , name = 'get-orders'),
    path('category/<category>', views.category_results, name="category"),
    path('delete/thread/<id>', views.delete_thread, name="delete-thread"),
    path('sort', views.sort_ads , name = 'sort'),
]

templates/furugi/account/ads.html
{% extends 'furugi/listings.html' %}
{% block extra_content %} 

<style>
  .modal {
    text-align: center;
    padding: 0!important;
  }
  
  .modal:before {
    content: '';
    display: inline-block;
    height: 100%;
    vertical-align: middle;
    margin-right: -4px;
  }
  
  .modal-dialog {
    display: inline-block;
    text-align: left;
    vertical-align: middle;
  }
</style>
        <div class="card-body">                                 
            <a href="ad-edit/{{data.id}}" class="btn btn-warning btn-sm" >Edit</a>
            <a href="" id="popup" data-toggle="modal" data-id="{{data.id}}" data-target="#deleteModal" class="btn btn-danger btn-sm">Delete</a>
        </div>
        <!-- Modal -->
         <div id="deleteModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <!-- Modal content-->
              <div class="modal-content"> 
                <div class="modal-header" style="background-color:red; ">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>                               
                <div class="modal-body">
                  <strong>Are you sure you want to delete this ad?</strong>
                </div>
                <div class="modal-footer">                  
                  <a href="" id="data" class="btn btn-danger btn-sm">Delete</a>
                  <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div> 
          <!-- End Modal -->
           
{% endblock %}

templates/furugi/account/block_profile.html
{% extends 'furugi/account/profile.html' %}

{% block button %}
    <a href="" class="btn btn-outline-danger" id="block" >Block this user</a>
{% endblock %}

templates/furugi/account/cart.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}
{% load static %}
{% include 'furugi/partials/mobile_menu.html' %}
<link rel="stylesheet" href=https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css>
<style>
  input[type=text] {
    border: none;
    border-bottom: 2px solid red;
  }
  input[readonly] {
    border:none; 
  }
  @media screen and (max-width: 600px) {
    .top {padding-top: 20%; padding-bottom: 5%;}
  }
</style>
<div class="site-section bg-light" style=" margin-top:10%">
  <div style="background:#F1F6FB;border:#D6DFD8 2px solid;color:#879F9F; margin-top:10%; font-size: 14px; height: 100px; width: 630px; margin-right:20%; margin-left:25%">
    <marquee behavior="alternate" direction="left" scrollamount="2"><span style="float: left; font-family: Oswald, Arial; padding: 0 0 0 2px;">See your Ad here. Email at contact@furugi.com.pk </span></marquee>
  </div>
      <div class="container" style="padding-right:15%;padding-left:15%">
      
      {% if not dresses  %}
      <div style="margin-top:5%; padding:20%; font-weight:bold">
        <h2 ><b>No items, Add some</b></h2>
        <a href="{% url 'furugi:ads' %}"> Shop Now</a>
      </div>
      {% else %}

       
        <div class="top" class="row mb-5" style="margin-top:7%;" >
          <div class="col-md-12 text-center border-primary" >
            <h2 class="font-weight-light text-primary">Cart</h2>
          </div>
      </div>
      {% include 'furugi/partials/notification.html' %}
           {% for data in dresses %}
    
           <div class="col-lg-12">
            <div class="d-block d-md-flex listing">
              <a href="{% url 'furugi:view' data.dress.id data.dress.slug %}" class="img d-block" style="background-image: url( '{{ data.dress.profile.url}}')"></a>
              <div class="lh-content">             
                <h3><a href="{% url 'furugi:view' data.dress.id data.dress.slug %}">{{ data.dress.title}}</a></h3>               
                <strong>Price: {{ data.dress.price}}</strong>
                <div style="float:right"><a href="{% url 'furugi:delete-item' data.dress.id %}" ><i class="fa fa-trash" style="color:maroon;"></i> </a></div>          
            </div>
            </div>
          </div>
            {% endfor %}
          <form action="{% url 'furugi:order' %}" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            <div class="col-lg-12">
              <div class="d-block d-md-flex listing">  
               
                <div class="lh-content"> 
                  <div class="row mb-5">
                    <div class="col-md-12 text-center border-primary" >
                      <h2 class="font-weight-light text-primary">Make sure all information is correct</h2>
                    </div>
                </div>
                   
                  <div class="row" style="text-align:center">
                   
                    <div class="col-lg-4" style="text-align:right; ">              
                      <b>Username:</b>
                    </div>
                    <div class="col-lg-6" style="float:left">  
                      <input class="form-control" value="{{user.username}}" readonly>            
                    </div>
                  </div>                      
                  <div class="row" style="text-align:center">
                    <div class="col-lg-4" style="text-align:right; ">              
                      <b>Email:</b>
                    </div>
                    <div class="col-lg-6" style="float:left">  
                      <input type="email" class="form-control" name="email" value="{{user.email}}" readonly>            
                    </div>
                  </div>
                  <div class="row" style="text-align:center">
                    <div class="col-lg-4" style="text-align:right; ">              
                      <b>Contact:</b>
                    </div>
                    <div class="col-lg-6" style="float:left">  
                      <input type="text" class="form-control" name="contact" value="{{details.contact}}" >            
                    </div>
                  </div>
                  <div class="row" style="text-align:center">
                    <div class="col-lg-4" style="text-align:right; ">              
                      <b>Address:</b>
                    </div>
                    <div class="col-lg-6" style="float:left">  
                      <input type="text" class="form-control" name="address" value="{{details.street}}" >            
                    </div>
                  </div>
                  <div class="row" style="text-align:center">
                    <div class="col-lg-4" style="text-align:right; ">              
                     
                    </div>
                    <div class="col-lg-3" style="float:left">  
                      <input type="text" class="form-control" value="{{details.city}}" >            
                    </div>
                    <div class="col-lg-3" style="float:left">  
                      <input type="text" class="form-control" value="{{details.country}}" >            
                    </div>
                  </div>
                 
                </div>
              </div>
            </div>
            <div class="col-lg-12" style="text-align:center">
              <button type="submit" class="btn btn-danger">Order</button>
            </div>
            </form>
        {% endif %}
        <div style="text-align:center; margin-top:5%" ><a href="{% url 'furugi:past-orders' %}" class="btn btn-default" style="width:70%; color:white; background-color:teal">Past Orders</a></div>

    </div>
</div>

         
 {% endblock %}   
    
 

templates/furugi/account/edit.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}
<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/3/jquery.inputmask.bundle.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% load static %}
<style>

    .col2 {
        width: 16.66% !important;
    }
    .col8 {
        width: 66.66% !important;
    }
    @media only screen and (max-width: 600px) {
        /* For mobile phones: */
        .col2 {
            width: 8.33% !important;
        }
        .col8 {
            width: 83.33% !important;
        }
    }
 
</style>
{% include 'furugi/partials/mobile_menu.html' %}
<div class="site-blocks-cover inner-page-cover overlay" style="background-image: url('{% static 'furugi/images/rent-clothes-online.jpeg' %}')" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-10" data-aos="fade-up" data-aos-delay="400">
        <div class="row justify-content-center mt-5">
          <div class="col-md-8 text-center">
            <h1>My Profile</h1>
            <p>Build trust by completing your profile as users with complete profile are trusted more</p>
          </div>
        </div>        
      </div>
    </div>
  </div>
</div>  
<div class="row">
    <div class="col2" >    
    
    </div>
<div class="col8" >
<div class="site-section bg-light" >
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-7 mb-5"  data-aos="fade">
         <a href="{% url 'password_change' %}" class="btn btn-outline-info waves-effect" style='float:right' >Change Password</a>

      <h4 class="mb-3">Add profile information</h4>
    <form action="{% url 'furugi:user-profile' %}" method="post" class="needs-validation" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
        <label for="username">Username</label>
        <div class="input-group">
            <div class="input-group-prepend">
            <span class="input-group-text">@</span>
            </div>
            <input type="text" class="form-control" id="username" value="{{user.username}}" readonly >            
        </div>
        </div>
        <div class="mb-3">
            <label for="email">Email </label>
            <input type="email" class="form-control" id="email" value="{{user.email}}" readonly>      
        </div>
        <div class="row form-group">
            <div class="col-md-12">
              <label class="text-black" >Contact Number</label>
              <div class="input-group">
                <div class="input-group-prepend">
                <span class="input-group-text">+92</span>
                </div>
                <input type="text" name="contact" class="form-control"  maxlength="10" pattern="[0-9]{10}" value="{{contact}}" required>            
            </div>
            </div>      
          </div>
        <div style="margin-top:10px; margin-bottom:10px;text-align: right">
            <div class="checkbox">            
                {% if details.contact_visible == True %}
                <label><input type="checkbox" name="contact_visible" checked><small>  Visible to public</small></label>
                {% else %}
                <label><input type="checkbox" name="contact_visible" ><small>  Visible to public</small></label>
                {% endif %}
            </div>
        </div> 
    
             <hr class="mb-4"> 
           <div class="row">          
            <div class="col-md-6 mb-3">
                <label for="gender">Gender </label>
                <select class="custom-select d-block w-100" id="gender" name="gender"  >
                {% if details.gender == "Female" %}
                    <option value="Female">Female</option>
                    <option value="Male">Male</option>
                    <option value="Not specified">Not specified</option>
                {% elif details.gender == "Male" %}
                    <option value="Male">Male</option>
                    <option value="Not specified">Not specified</option>
                    <option value="Female">Female</option>
                {% else %}
                    <option value="Not specified">Not specified</option>
                    <option value="Female">Female</option>
                    <option value="Male">Male</option>
                {% endif %}
                </select>          
            </div>       
            <div class="col-md-6 mb-3">
                <label for="id">ID Card No <span class="text-muted">(without dashes)</span></label>               
                <input type="text" class="form-control" data-inputmask="'mask': '9999999999999'" id="id" maxlength="13" name="cnic" value="{{details.id_card_no}}" >                   
            </div>       
        </div>      
 
         <hr class="mb-4"> 
        <div class="mb-3">
            <label for="street">Street Address </label>
            <input type="text" class="form-control" id="street" name="street" value="{{details.street}}" >       
        </div>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="city">City</label>
                <input id="cityInput" type="text" class="form-control" name="city" value="{{details.city}}" >
   
            </div>              
        
            <div class="col-md-6 mb-3">
                <label for="country">Country </label>
                <select class="custom-select d-block w-100" id="country" name="country" value="{{details.country}}" >
                    {% if details.country %}
                       <option value="{{details.country}}">{{details.country}}</option>
                    {% else %}
                        <option value="">Choose...</option>
                    {% endif %}
                    <option value="Pakistan" selected> Pakistan</option>
                </select>
            </div> 
        </div>
        
        <hr class="mb-4">
              
        <button type="submit"  class="btn btn-primary btn-lg btn-block">Update Information</button>
       </form>
    </div>
    </div>
    </div>
    </div>
</div>
<div class="col2">
</div>
</div>
    <script>
        $(":input").inputmask();
    </script>
  {% endblock %}   

templates/furugi/account/favorites.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}  
{% load static %}
<div class="site-mobile-menu">
  <div class="site-mobile-menu-header">
    <div class="site-mobile-menu-close mt-3">
      <span class="icon-close2 js-menu-toggle"></span>
    </div>
  </div>
  <div class="site-mobile-menu-body"></div>
</div>
<div class="site-blocks-cover overlay" style="background-image: url('{% static 'furugi/images/online-shopping-in-pakistan.jpeg' %}');" data-aos="fade" data-stellar-background-ratio="0.5">
  <div class="container">
    <div class="row align-items-center justify-content-center text-center">
      <div class="col-md-12">
        <div class="row justify-content-center mb-4">
          <div class="col-md-8 text-center">
            <h1 class="" data-aos="fade-up">Don't wait to lose it</h1>
            <p data-aos="fade-up" data-aos-delay="100">Grab it at first place</p>
          </div>
        </div>
        {% include 'furugi/partials/search.html' %}
      </div>
    </div>
  </div>
</div> 

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-10">
            {% include 'furugi/partials/notification.html' %}
            <div class="row">
              {% for data in dresses %}                          
                  <div class="col-lg-3">                
                    <div class="d-block d-md-flex listing vertical">
                      <a href="{% url 'furugi:view' data.dress.id data.dress.slug %}" class="img d-block" style="background-image: url( '{{ data.dress.profile.url}}')"></a>
                      <div class="lh-content">                   
                        <span class="category">  {{ data.dress.category}}</span>
                        <a href="{% url 'furugi:remove-favorites' data.dress.id %}" class="bookmark" data-toggle="tooltip" title="Remove from favorites"><span class="icon-close" ></span></a>
                        <h3><a href="{% url 'furugi:view' data.dress.id data.dress.slug%}">{{ data.dress.title}}</a></h3>
                        {% if data.dress.description == '' %}
                        <address > (no description)</address>
                        {% else %}
                        <address >  {{ data.dress.description}}</address>        
                        {% endif %}   
                        {% include 'furugi/advertisment/rating.html' %}    
                          <strong>Price: {{ data.dress.price}}</strong>
                          <span class="review" style="float:right"><em><small> ({{ data.dress.views}} Views)</small></em></span>   
                          <div>                                       
                          {% for tag in data.dress.tags.all %}
                          <a href="{% url 'furugi:tagged' tag.slug %}" class="mr-1 badge badge-info">{{ tag.name }}</a>
                        {% endfor %}  
                          </div> 
                           
                      
                         <div class="fb-share-button" data-href="https://www.furugi.com.pk/ad-view/{{data.id}}" data-layout="button_count" data-size="small"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fwww.furugi.com.pk%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div>
               </div>
                    </div>    
                  </div>
              {% endfor %}
            </div>

            {% include 'furugi/partials/pagination.html' %}

          </div>
          {% include 'furugi/partials/sidebar.html' %} 
        </div>
      </div>
    </div>

    {% include 'furugi/partials/trending.html' %}
    {% include 'furugi/partials/testimonials.html' %}  
    
  {% endblock %}

templates/furugi/account/past_orders.html
{% extends 'furugi/partials/base.html' %}
{% block main_content %}
{% load static %}
{% include 'furugi/partials/mobile_menu.html' %}
<link rel="stylesheet" href=https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css>
<style>
  @media screen and (max-width: 600px) {
    .top {padding-top: 20%;}
  }
</style>
<div class="site-section bg-light">
  <div style="background:#F1F6FB;border:#D6DFD8 2px solid;color:#879F9F; margin-top:10%; font-size: 14px; height: 100px; width: 630px; margin-right:20%; margin-left:25%">
    <marquee behavior="alternate" direction="left" scrollamount="2"><span style="float: left; font-family: Oswald, Arial; padding: 0 0 0 2px;">See your Ad here. Email at contact@furugi.com.pk </span></marquee>
  </div>
    <div class="container" >
      {% if not ordersD and not ordersND  %}
      <div style="margin-top:5%; padding:20%; font-weight:bold">
        <h2 ><b>No past orders, Create order now</b></h2>
        <a href="{% url 'furugi:ads' %}"> Shop Now</a>
      </div>
      {% else %}

        {% include 'furugi/partials/notification.html' %}
        <div class="top" class="row mb-5" >
          <div class="col-md-12 text-center border-primary" >
            <h2 class="font-weight-light text-primary">Newly Created</h2>
          </div>
      </div>
        <div>          
           {% for data in ordersND %}
    
           <div class="col-lg-12">
            <div class="d-block d-md-flex listing">
              <a href="{% url 'furugi:view' data.dress.id data.dress.slug %}" class="img d-block" style="background-image: url( '{{ data.dress.profile.url}}')"></a>
              <div class="lh-content">             
                <h3><a href="{% url 'furugi:view' data.dress.id data.dress.slug %}">{{ data.dress.title}}</a></h3>               
                <strong>Price:</strong> {{ data.dress.price}}
                <div><strong>Date Ordered:</strong> {{ data.date}}</div>
                <div><strong>Responsible:</strong> {{ data.responsible}}</div>
                <div style="text-align:right">
                  {% if data.dispatched == 0 %}
                      <a href="{% url 'furugi:cancel' data.id %}" class="btn btn-outline-danger btn-sm">Cancel </a>
                  {% else %}
                      <a style="color:gold">On its way to you</a>
                  {% endif %}
              
                </div>
              </div>
            </div>
          </div>
            {% endfor %}
            <hr>
            <div class="row mb-5">
                <div class="col-md-12 text-center border-primary" >
                  <h2 class="font-weight-light text-primary">Delivered</h2>
                </div>
            </div>
            {% for data in ordersD %}
    
           <div class="col-lg-12">
            <div class="d-block d-md-flex listing">
              <a href="{% url 'furugi:view' data.dress.id data.dress.slug %}" class="img d-block" style="background-image: url( '{{ data.dress.profile.url}}')"></a>
              <div class="lh-content">             
                <h3><a href="{% url 'furugi:view' data.dress.id data.dress.slug %}">{{ data.dress.title}}</a></h3>               
                <strong>Price:</strong> {{ data.dress.price}}
                <div><strong>Date Ordered:</strong> {{ data.date}}</div>
                <div><strong>Responsible:</strong> {{ data.responsible}}</div>
                <div><strong>Date Delivered:</strong> {{ data.date_delivered}}</div>
              </div>
            </div>
          </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

         
 {% endblock %}   
    
 

templates/furugi/account/profile.html
 {% load static %}
 <!-- Modal -->

 <div class="modal fade" id="profile" role="dialog" >
    {% if not user.is_authenticated %}
    <div class="modal-dialog">
        <div class="modal-content"> 
            <div class="modal-header" style="background-color:gainsboro">
                <h5 class="modal-title" style="font-weight:bold">Attention</h5>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body" style="text-align:center; border-bottom: 1px">
               <a href="{% url 'furugi:login' %}">Login</a> first to view advertiser profile 
            </div>                       
        </div>
    </div>
    {% else %}
    <div class="modal-dialog" style="overflow-y: scroll; max-height:85%;  margin-top:50px; margin-bottom:50px;  overflow-y: initial !important; ">
      <div class="modal-content">
        <div class="modal-header" style="background-color:#30e3ca; ">
            <h5 class="modal-title" style="font-weight:bold; color:white">Advertiser Profile</h5>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body" id="profile-body" style=" height: 400px; overflow-y: auto;">
                <div class="row">
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">Username</label>
                    </div>
                    <div class="col-md-8 col-6" id="username">
                        {{dress.user.username}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">Email</label>
                    </div>
                    <div class="col-md-8 col-6" id="email">
                        {{dress.user.email}}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">Gender</label>
                    </div>
                    <div class="col-md-8 col-6" id="gender">
                        {{dress.gender}}
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">Street</label>
                    </div>
                    <div class="col-md-8 col-6" id="street">
                        {{details.street}}
                    </div>
                </div>              
                <div class="row">
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">City</label>                  
                    </div>                                
                    <div class="col-md-8 col-6">
                        {{details.city}}
                    </div> 
                </div>
                <div class="row">
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">Country</label>                      
                    </div>                                
                    <div class="col-md-8 col-6">                        
                        {{details.country}}
                    </div> 
                </div>
                
                <hr class="mb-4">
                {% if details.contact_visible == True %}
                <div class="row">  
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">Contact:</label>
                    </div>
                    <div class="col-md-8 col-6" >   {{details.contact}}                    
                    </div>                                   
                </div>
                {% endif %}
                <div class="row">  
                    <div class="col-sm-3 col-md-2 col-5">
                        <label style="font-weight:bold;">CNIC:</label>
                    </div>
                    <div class="col-md-8 col-6" id="cnic">   {{details.id_card_no}}                    
                    </div>                                   
                </div>
            
        </div>
        <div class="modal-footer">
          <div>
            {% block button %}
            {% endblock %}
           </div>
        </div>
      </div>
    
    </div>
    
    {% endif %}
  </div>
 
  

templates/furugi/account/report.html
<div id="report" class="modal" >
    <div class="modal-dialog" style="border: 1px solid;">
        <div class="modal-header" style="background-color:#30e3ca; ">
            <h5 class="modal-title" style="font-weight:bold; color:white">Report Advertiser</h5>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-content" style="border:3px solid white" >         
            <form action="{% url 'furugi:report' dress.user_id dress.id %}" method="post" enctype="multipart/form-data" >
                {% csrf_token %}             
            <div class="modal-body">
               <textarea class="form-control" col='5' rows="3" name='report' maxlength="2000" placeholder="Report The Issue....."></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-outline-danger">Send</a>
            </div>
            </form>
        </div>
    </div>
</div>